import { AUTH_PAGE_URL } from "@/constants/pageUrl";

const {
  FORGOT_PASSWORD,
  FORGOT_PASSWORD_SUCCESS,
  LOGIN,
  RESET_PASSWORD,
  RESET_PASSWORD_SUCCESS,
} = AUTH_PAGE_URL;

export const whitelistPaths = [
  LOGIN,
  FORGOT_PASSWORD,
  FORGOT_PASSWORD_SUCCESS,
  RESET_PASSWORD,
  RESET_PASSWORD_SUCCESS,
];
